### ISSUE TITLE
feature request: gamification

### ISSUE THREAD

**Issue by herrvonvoid** [fkinoshita/Wildcard#15]
The logo and description on flathub somehow gave me the impression this was some kind of regex trainer or game. i expected a game like this: the player sees the back of the card from the logo, when he clicks and truns it a counter starts and he can see a random text with a random highlighted part which he now has to match with a regex exactly. as soon as he enters a matching regex the time is shown and maybe a ranking amongst the previous attempts.

**Comment by fkinoshita** [comment]
Sorry for setting up the wrong expectations for Wildcard, I won't turn it into a game though.
