### ISSUE TITLE
caret not displayed in regex input field

### ISSUE THREAD

**Issue by olivierf77** [fkinoshita/Wildcard#16]
Nice concept :-)
However, in the regex input field, the caret is not displayed. Dark mode tested.
--
OS:  Linux x64 Opensuse Tumbleweed. Up-to-date. 
GUI: KDE - Plasma - Dark Breeze. Up-to-date. 
HW:  Intel i6700K (not OC) - RAM 32 GB - NVME Samsung 1TB

**Comment by fkinoshita** [comment]
It's displayed correctly here, is your Plasma theme also applying to GTK applications?

**Comment by olivierf77** [comment]
After extensive testing.
Tested 2 GTK apps:
- GParted: chooses its own own (light) colors. Caret displayed in its light input field.
- Gedit: follows the general KDE Plasma themes.
- In dark mode, unusable, since the colors displayed do not match the Plasma conventions. Kate, a qt based editor, works flawlessly.
- In Light mode, works OK.

Your app (Wildcard):
- In Light mode themes (such as Breeze classic): caret displayed.
- In Dark mode (such as Breeze dark and other dark themes): Caret not displayed, or rather probably displayed in dark, unreadable color, rather than a light color.

-> either the mistake is yours, or it is a bug in Plasma/GTK color matching in all dark modes
-> suggested workaround: Let the user chose a light mode, independently of the general theme dark/light.

**Comment by fkinoshita** [comment]
Could you please send a screenshot showing the issue? It's not on my end and likely something regarding your custom setup.
