### ISSUE TITLE
the very important meta character '.' is not taken into account in the regex expression

### ISSUE THREAD

**Issue by olivierf77** [fkinoshita/Wildcard#18]
metacharacter '.' means any character, and as such, allows expressions such as 'ab.*cd', which would select any string starting with 'ab' and ending with 'cd'.
In the present state, this does not seem possible.
--
OS:  Linux x64 Opensuse Tumbleweed. Up-to-date. 
GUI: KDE - Plasma - Dark Breeze. Up-to-date. 
HW:  Intel i6700K (not OC) - RAM 32 GB - NVME Samsung 1TB

**Comment by olivierf77** [comment]
Furthermore, you then have to implement the greedy/not greedy flag.
Greedy: '.*' the expression gobbles as many characters as possible.
Not greedy: '.*' the expression googles as few characters as possible.

**Comment by fkinoshita** [comment]
That's already possible with the regex/FLAGS syntax, I still need to implement a nice dialog for all the flags though.
