### ISSUE TITLE
the very important meta character '.' is not taken into account in the regex expression (closed, probably by mistake, by app author)

### ISSUE THREAD

**Issue by olivierf77** [fkinoshita/Wildcard#20]
This issue was closed by author, but issue remains,
so closed probably by mistake.

metacharacter '.' means any character, and as such, allows expressions such as 'ab.*cd', which would select any string starting with 'ab' and ending with 'cd'.
In the present state, this does not seem possible.

Also, the greedy/not greedy is not only a flag, it may immediately follows a *, such as
ab. *de -> selects abde, ab&lt;maximum number of chars&gt;de
ab. *?de -> selects abde, ab&lt;minimum number of chars&gt;de

And, regarding flags, you are right: 
they DO work (/I or /i taken into account in your app).
--
OS: Linux x64 Opensuse Tumbleweed. Up-to-date.
GUI: KDE - Plasma - Dark Breeze. Up-to-date.
HW: Intel i6700K (not OC) - RAM 32 GB - NVME Samsung 1TB

**Comment by olivierf77** [comment]
Update, because char &gt; and &lt; where ignrored
ab.de -> selects abde, ab(maximum number of any char)de
ab.?de -> selects abde, ab(minimum number of any char)de

**Comment by fkinoshita** [comment]
> metacharacter '.' means any character, and as such, allows expressions such as 'ab.*cd', which would select any string starting with 'ab' and ending with 'cd'.
In the present state, this does not seem possible.

That's possible, you need to turn on the Unicode flag, that seems to be something specific regarding the rust regex library.

![image](https://github.com/fkinoshita/Wildcard/assets/126302554/4b344406-4a9d-46e7-9ce2-f182d0f67fde)
