### ISSUE TITLE
[Feature Request] AUR repository for arch users

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [fkinoshita/Wildcard#35]
Hey, 
it would be very handy to have your app in the AUR (Arch user repository). This eases the installation process a lot for arch users :)
I don't know if you have any experience with that or are even willing to maintain that. 
Thanks for your great gnome app!

**Comment by fkinoshita** [comment]
Hi, sorry but I don't plan to have this app in the AUR, anyone is still welcome to do so but the recommended way to use the app is through flatpak.
Thank you for the kind words!
